- name: Run simple-api container
  docker_container:
    name: simple-api
    image: mellou/tp-devops-simple-api:latest
    pull: true
    recreate: true
    force_kill: true
    state: started
    ports:
      - "8080:8080"
    restart_policy: always
    env:
      DATABASE_HOST: "{{ app_db_host }}"
      DATABASE_PASSWORD: "{{ app_db_password }}"
    networks:
      - name: my-network
