db_user: "{{ lookup('env', 'DB_USER') }}"
db_password: "{{ lookup('env', 'DB_PASSWORD') }}"
app_db_host: "{{ lookup('env', 'APP_DB_HOST') }}"
app_db_password: "{{ lookup('env', 'APP_DB_PASSWORD') }}"
