name: CD - Docker build and push

on:
  workflow_run:
    workflows: ["CI - Test backend"]
    types:
      - completed

jobs:
  build-and-push-docker-image:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image and push backend
        uses: docker/build-push-action@v6
        with:
          context: TP/TP2/tp-devops-correction-docker/simple-api
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-simple-api:latest
          push: true

      - name: Build image and push httpd
        uses: docker/build-push-action@v6
        with:
          context: TP/TP2/tp-devops-correction-docker/http-server
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-httpd:latest
          push: true

      - name: Build image and push database
        uses: docker/build-push-action@v6
        with:
          context: TP/TP2/tp-devops-correction-docker/database
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-database:latest
          push: true
      - name: Build and push front
        uses: docker/build-push-action@v6
        with:
          context: TP/TP2/tp-devops-correction-docker/front
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-front:latest
          push: true
